### ISSUE TITLE
Data from the API should be displayed nicely

### ISSUE THREAD

**Issue by MichaelKohler** [MichaelKohler/community_dashboard_participation#4]
Maybe we can go with a table with all the data for now? Maybe some chart for the top skill sets?

**Comment by SOFTowaha** [comment]
I think, data with tables is cool. But how about Pictures / Metaphors [to present data visually]? 
I guess it can be done after collecting the iinformation.

**Comment by MichaelKohler** [comment]
I think a table is fine enough to fulfill the requirements (since it's not much data to display), but I think the richer the better :D

**Comment by SOFTowaha** [comment]
+1
